#!/usr/bin/env python3
"""Rasterize Natural Earth 110m land polygons to a 1-bit equirectangular
landmask sized for the photonichat sunmap canvas (640x172, stretched).

Output: main/landmask.h with a static const uint8_t array, MSB-first packing,
        one bit per pixel, row-major.

Run from repo root:
    python3 scripts/gen_landmask.py
"""

import os
import sys
import urllib.request
import zipfile
import io
from pathlib import Path

import shapefile  # pyshp
from PIL import Image, ImageDraw

# Sized to the live canvas (canvas_w x canvas_h). The sunmap stretches to fill
# this area, so the mask is sampled 1:1 with no scaling at runtime.
W = 640
H = 172

NE_URL = (
    "https://naciscdn.org/naturalearth/110m/physical/"
    "ne_110m_land.zip"
)

REPO_ROOT = Path(__file__).resolve().parent.parent
CACHE_DIR = REPO_ROOT / "scripts" / ".cache"
SHP_DIR = CACHE_DIR / "ne_110m_land"
OUT_HEADER = REPO_ROOT / "main" / "landmask.h"


def fetch_natural_earth() -> Path:
    SHP_DIR.mkdir(parents=True, exist_ok=True)
    shp = SHP_DIR / "ne_110m_land.shp"
    if shp.exists():
        return shp
    print(f"downloading {NE_URL}", file=sys.stderr)
    with urllib.request.urlopen(NE_URL) as r:
        data = r.read()
    with zipfile.ZipFile(io.BytesIO(data)) as zf:
        zf.extractall(SHP_DIR)
    return shp


def lonlat_to_px(lon: float, lat: float) -> tuple[float, float]:
    # Equirectangular, stretched to W x H.
    x = (lon + 180.0) / 360.0 * W
    y = (90.0 - lat) / 180.0 * H
    return x, y


def rasterize(shp_path: Path) -> bytes:
    img = Image.new("1", (W, H), 0)  # 0 = ocean
    draw = ImageDraw.Draw(img)

    sf = shapefile.Reader(str(shp_path))
    shapes = sf.shapes()
    poly_count = 0
    for shape in shapes:
        # Each shape may have multiple parts (separate rings / islands).
        parts = list(shape.parts) + [len(shape.points)]
        for i in range(len(parts) - 1):
            ring = shape.points[parts[i]:parts[i + 1]]
            if len(ring) < 3:
                continue
            pts = [lonlat_to_px(lon, lat) for lon, lat in ring]
            draw.polygon(pts, fill=1, outline=1)
            poly_count += 1

    print(f"rasterized {poly_count} rings into {W}x{H}", file=sys.stderr)
    return img.tobytes()  # PIL "1" mode: MSB-first packed, padded per row


def pack_msb_no_row_padding(img_bytes: bytes) -> bytes:
    # PIL "1" mode pads each row to a byte. Repack tightly: row-major,
    # MSB-first, no padding between rows. Total = ceil(W*H / 8) bytes.
    img = Image.frombytes("1", (W, H), img_bytes)
    pixels = img.load()
    total_bits = W * H
    out = bytearray((total_bits + 7) // 8)
    for y in range(H):
        for x in range(W):
            if pixels[x, y]:
                bit_idx = y * W + x
                out[bit_idx >> 3] |= 0x80 >> (bit_idx & 7)
    return bytes(out)


def emit_header(packed: bytes) -> str:
    n = len(packed)
    lines = []
    lines.append("/* Auto-generated by scripts/gen_landmask.py. Do not edit by hand. */")
    lines.append("/* Source: Natural Earth 1:110m physical land (public domain). */")
    lines.append("#ifndef LANDMASK_H")
    lines.append("#define LANDMASK_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define LANDMASK_W {W}")
    lines.append(f"#define LANDMASK_H {H}")
    lines.append(f"#define LANDMASK_BYTES {n}")
    lines.append("")
    lines.append("/* Row-major, MSB-first, 1 bit per pixel. bit=1 => land. */")
    lines.append("static const uint8_t k_landmask[LANDMASK_BYTES] = {")
    per_line = 16
    for i in range(0, n, per_line):
        chunk = packed[i:i + per_line]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("static inline int landmask_get(int x, int y) {")
    lines.append("    if ((unsigned)x >= (unsigned)LANDMASK_W) return 0;")
    lines.append("    if ((unsigned)y >= (unsigned)LANDMASK_H) return 0;")
    lines.append("    int bit = y * LANDMASK_W + x;")
    lines.append("    return (k_landmask[bit >> 3] >> (7 - (bit & 7))) & 1;")
    lines.append("}")
    lines.append("")
    lines.append("#endif /* LANDMASK_H */")
    return "\n".join(lines) + "\n"


def main() -> int:
    shp = fetch_natural_earth()
    raw = rasterize(shp)
    packed = pack_msb_no_row_padding(raw)
    header = emit_header(packed)
    OUT_HEADER.write_text(header)
    print(f"wrote {OUT_HEADER} ({len(packed)} bytes payload)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
